DYNAMIC_TABLE_FAILURE_QUERY = """
SELECT
    NAME,
    DATABASE_NAME,
    SCHEMA_NAME,
    STATE,
    DATA_TIMESTAMP
FROM SNOWFLAKE.ACCOUNT_USAGE.DYNAMIC_TABLE_REFRESH_HISTORY
WHERE STATE = 'FAILED'
  AND DATA_TIMESTAMP >= DATEADD('hour', -2, CURRENT_TIMESTAMP())
ORDER BY DATA_TIMESTAMP DESC;
"""